cliente/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('add_cliente/',views.add_cliente,name='add_cliente_url'),
    path('criar_cliente/',views.criar_cliente,name='criar_cliente'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('produto/',include('produto.urls')),
    path('produto_variavel/',include('produto_variavel.urls')),
    path('molde/',include('molde.urls')),
    path('ordem_servico/',include('ordem_servico.urls')),
    path('cliente/',include('cliente.urls')),
    path('pedido/',include('pedido.urls')),
    
]
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cliente/models.py
from django.db import models

class Cliente(models.Model):
    nome=models.CharField(max_length=50)
    whatsapp = models.CharField(max_length=15)
    endereco=models.CharField(max_length=50)

    def __str__(self):
        return self.nome

cliente/forms.py
from django import forms
from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'whatsapp', 'endereco']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'  # Adiciona a classe 'form-control' a todos os campos

cliente/views.py
from django.shortcuts import render,redirect
from .models import Cliente

def add_cliente(request):

    clientes = Cliente.objects.all()

    return render(request, 'add_cliente2.html',{'clientes':clientes})

from django.shortcuts import render, redirect
from .forms import ClienteForm

def criar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('nome_da_view')  # Redirecionar para a página desejada após salvar o cliente
    else:
        form = ClienteForm()
    return render(request, 'add_cliente.html', {'form': form})

cliente/templates/add_cliente.html
{% extends "base.html" %}

{% block title %}Cliente{% endblock title %}

{% block head %}
<style>
    body {
        background-color: #ebeef2 !important; /* Cor de fundo da tela como cinza claro */
    }
    .custom-form {
        max-width: 600px;
        margin: 60px auto 0; /* Adiciona margem superior para afastar do menu */
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0,0,0,0.1);
        background-color: #fff; /* Cor de fundo do formulário como branco */
    }

    .title-box {
        background-color: #007bff; /* Cor de fundo do retângulo azul */
        padding: 10px;
        border-radius: 5px;
        color: #fff; /* Cor do texto como branco */
        text-align: center;
        margin-bottom: 40px; /* Adiciona margem inferior ao retângulo azul */
    }

</style>

{% endblock head %}

{% block content %}
 
    
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="custom-form " style="background-color: #fff;">
                
                <div class="title-box">
                    <h2 class="mt-0">Criar Cliente</h2> <!-- Removendo a margem superior do título -->
                </div>
                
                <form method="post">
                    {% csrf_token %}
                    <div class="row mb-3">
                        <div class="col">
                            <label for="id_nome" class="form-label">Nome:</label>
                            {{ form.nome }}
                        </div>
                        <div class="col">
                            <label for="id_whatsapp" class="form-label">WhatsApp:</label>
                            {{ form.whatsapp }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="id_endereco" class="form-label">Endereço:</label>
                        {{ form.endereco }}
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </form>
            </div>
        </div>
    </div>
        
{% endblock content %}

{% block js %}{% endblock js %}

cliente/templates/add_cliente2.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<!-- This script got from frontendfreecode.com -->

<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.2/css/bootstrap.min.css'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
<style>
* {
	font-family: "Poppins", sans-serif;
}
body {
	background-image: linear-gradient( to left bottom, #051937, #05162f, #051327, #040f1f, #010a18);
	background-size: 800%;
	animation: animateClr 1s infinite cubic-bezier(0.62, 0.28, 0.23, 0.99);
}
input[type="text"], input[type="email"], input[type="tel"], textarea {
	border: none;
	border-bottom: 2px solid rgb(128, 126, 126);
	background: transparent;
	outline: none;
	width: 100%;
	text-transform: capitalize;
	padding: 1rem 0.4rem;
}
.aside {
	background-image: linear-gradient( to left bottom, #051937, #002350, #002d69, #003684, #01409f);
	animation: animateClr 5s infinite cubic-bezier(0.62, 0.28, 0.23, 0.99);
	background-size: 400%;
}
@keyframes animateClr {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}
</style>

</head>
<body>
<div class="container">
    <div class="bg-light">
        <div class="row">
            <div class="col-lg-8 col-md-12 p-5 bg-white rounded-3">
                <div class="d-flex mb-3 flex-column">
                    <h1 class="h5 text-capitalize my-4">What service You need ?</h1>
                    <div class="d-flex flex-wrap">
                        <div class="d-flex flex-wrap justify-content-center align-items-center me-4">
                            <input type="checkbox" name="webdev" class="form-check-input m-0 me-3" id="webdev" />
                            <label for="webdev"> Web Development</label>
                        </div>
                        <div class="d-flex flex-wrap justify-content-center align-items-center me-4">
                            <input type="checkbox" name="webdes" class="form-check-input m-0 me-3" id="webdes" />
                            <label for="webdes"> Web Design</label>
                        </div>
                        <div class="d-flex flex-wrap justify-content-center align-items-center me-4">
                            <input type="checkbox" name="logodes" class="form-check-input m-0 me-3" id="logodes" />
                            <label for="logodes"> Logo Design</label>
                        </div>
                        <div class="d-flex flex-wrap justify-content-center align-items-center me-4">
                            <input type="checkbox" name="others" class="form-check-input m-0 me-3" id="others" />
                            <label for="others"> Others </label>
                        </div>
                    </div>
                </div>
                <form class="row mb-3">
                    <div class="col-md-6 p-3">
                        <input required placeholder="first name" type="text" name="" id="" />
                    </div>
                    <div class="col-md-6 p-3">
                        <input required placeholder="last name" type="text" name="" id="" />
                    </div>
                    <div class="col-md-6 p-3">
                        <input required placeholder="E-mail" type="email" name="" id="" />
                    </div>
                    <div class="col-md-6 p-3">
                        <input required placeholder="phone" type="tel" name="" id="" />
                    </div>
                    <div class="col-md">
                        <textarea required name="" placeholder="write your message" id="" cols="30" rows="1"></textarea>
                    </div>
                    <div class="text-end mt-4">
                        <input class="btn px-4 py-3 btn-outline-dark" type="submit" value="Send Message" />
                    </div>
                </form>
            </div>
            <div class="col-lg-4 col-md-12 text-white aside px-4 py-5">
                <div class="mb-5">
                    <h1 class="h3">Contact Information</h1>
                    <p class="opacity-50">
                        <small>
                            Fill out the from and we will get back to you whitin 24 hours
                        </small>
                    </p>
                </div>
                <div class="d-flex flex-column px-0">
                    <ul class="m-0 p-0">
                        <li class="d-flex justify-content-start align-items-center mb-4">
                            <span class="opacity-50 d-flex align-items-center me-3 fs-2">
                                <i class="fa fa-phone"></i>
                            </span>
                            <span>+134 1234 1234</span>
                        </link>
                        <li class="d-flex align-items-center r mb-4">
                            <span class="opacity-50 d-flex align-items-center me-3 fs-2">
                                <i class="fas fa-mail-bulk"></i>
                            </span>
                            <span>Help@contact.com</span>
                        </li>
                        <li class="d-flex justify-content-start align-items-center mb-4">
                            <span class="opacity-50 d-flex align-items-center me-3 fs-2">
                                <i class="fa-solid fa-location-pin"></i>
                            </span>
                            <span>
                                52 Buddy Ln Conway, <br />
                                Arkansas(AR), 72032
                            </span>
                        </li>
                    </ul>
                    <div class="text-muted text-center">
                        <code>
                            Your Logo
                        </code>
                        <br />
                        <code>Created By : Company Name </code> <br />
                        <code>
                        </code>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><div id="bcl"><a style="font-size:8pt;text-decoration:none;" href="http://www.devanswer.com">Free Frontend</a></div>

</body>
</html>